server:
  port: 8089
  servlet:
    context-path: /
spring:

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/demoshopping?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis.cfg.xml

jackson:
        time-zone: GMT+8
